### ISSUE TITLE
can't use on typescript

### ISSUE THREAD

**Issue by jakemraz** [opticdev/optic-node#19]
I'm using optic on the ts-node project. (https://github.com/santiq/bulletproof-nodejs)

```
import OpticMiddleware from '@useoptic/express-middleware';
app.use(OpticMiddleware({
    enabled: process.env.NODE_ENV !== 'production',
  }));
```

But above code has an error below
```
Type 'boolean' is not assignable to type 'false'.ts(2322)
index.d.ts(3, 5): The expected type comes from property 'enabled' which is declared here on type 'Options'
(property) Options.enabled?: false
```

So when I looked at `node_modules/@useoptic/express-middleware/dist/index.d.ts`, and its code is compiled as below
```
import express from 'express';
interface Options {
    enabled?: false;
    console?: false;
    log?: false;
    uploadUrl?: string;
}
declare const _default: (options: Options) => (req: express.Request, res: express.Response, next: express.NextFunction) => Promise<void>;
export default _default;
//# sourceMappingURL=index.d.ts.map
```

I'm a newbie for typescript so I don't know why the attributes of `Options` interface have `false` type instead of `boolean` type.
After I fixing `false` to `boolean`, it works. But I have no idea how to fix this on the code.

My node version is v.14.17.3.

Please let me know how to fix it.

Thanks!!

**Comment by ukmadlz** [comment]
Hi @jakemraz which version are you using? The latest `0.0.5` release should contain the fix https://www.npmjs.com/package/@useoptic/express-middleware/v/0.0.5

**Comment by jakemraz** [comment]
Thanks I've just checked it works.
